### ISSUE TITLE
Name confusion

### ISSUE THREAD

**Issue by ederag** [mgerstner/hamster#1]
Thanks for contributing to FreeSoftware ! And I really like openSUSE, in general.
As the current maintainer of [hamster](https://github.com/projecthamster/hamster), a time tracker first released in 2007,
I'd like to draw your attention to a potential confusion that might arise if
an unrelated software is called `hamster` as this repo, or even [hamster-security](https://pypi.org/project/hamster-security/) as released on pypi.
We already have a whole ecosystem of `hamster-*` related projects,
in https://github.com/projecthamster as well as
[hamster-bridge](https://github.com/kraiz/hamster-bridge)
[hamster-to-harvest](https://github.com/olange/hamster-to-harvest)
[hamster-snap](https://github.com/extraymond/hamster-snap)
[hamster-tool](https://github.com/GeraldJansen/hamster-tool)

Would you please consider changing the name so that it would not start with `hamster-`,
and if you really want to keep `hamster` somewhere in the name,
adding at the top of the README something like
"*This project is totally unrelated to the hamster time tracker*" ?

**Comment by mgerstner** [comment]
Thank you for bringing this to my attention. I did do a check for name colissions and it looked to me like no major OSS software uses the plain "hamster". I turns out there a few by know, or a few that I overlooked like:

<pre>
- pypi: hamster (0.1dev)          - Hamster - Nice and friendly movie collection manager
- dev-ruby/hamster                  - Efficient, immutable, thread-safe collection classes for Ruby
</pre>

And of course yours. Are there already practical issues with this name clash or is this just a precaution on your side?

It's unfortunate that we didn't realize the name clash. Changing the name will require some time. I'm sorry for the inconvenience.

**Comment by ederag** [comment]
Understood.

Indeed, there are plans to kindly try to reclaim the https://pypi.org/project/hamster/ package name,
since it has not been touched in about 7 years.
The [hamstergem/hamster](https://github.com/hamstergem/hamster) unfortunately raises some questions as well, but at least it is in ruby, not python.

> Are there already practical issues with this name clash or is this just a precaution on your side?

in some sense confusion *is* "practical",
but no-one tried to install both packages,
so please take your time to change the name peacefully.

**Comment by mgerstner** [comment]
I've renamed the complete project and also the PyPi package. This should resolve your concern. The main repository was actually at openSUSE/hamster, this here is just my personal fork. I will delete it.
